### PR TITLE
Add possibility to configure environment variables

### PR DESCRIPTION
**Pull request by PatrickGotthard**
Adds support for passing environment varianbles to App Runner instances.
See #4

### CODE REVIEW

**Comment by PatrickGotthard** [comment]
Currently it is not possible to update the environment variables for code-based instances.
I don't know why there's currently no routine for updating code-based services.

**Comment by hariohmprasath** [comment]
Hi @PatrickGotthard,
Thanks for the contribution. The code looks good to me, can you add a couple of test cases to `index.test.ts`?

@DmitryGulin,
Can you review it once as well? Thanks

**Comment by DmitryGulin** [comment]
Agree with @hariohmprasath , let's have the new functionality covered with tests first.

**Comment by PatrickGotthard** [comment]
Hi @DmitryGulin, @hariohmprasath,

I'll add tests as soon as possible. I looked at the existing tests and it should be not that hard - even though I'm no JavaScript expert. But it would be much easier to write tests for changes like this when the config and deploy parts would be decoupled from each other - but that requires a major rewrite of the code.

Regards,
Patrick

**Comment by PatrickGotthard** [comment]
Hi @DmitryGulin, @hariohmprasath,

in the meantime I rewrote the action from scratch because I found the code hard to read/maintain and we also had to add support for autoscaling while also not being interested in code-based deployments.
Do you want to fork this pull-request or should I just close this pull-request?

Regards,
Patrick

**Comment by hariohmprasath** [comment]
Thanks for the response @PatrickGotthard, let's close this pull request and when you get a chance you can work on making your code backward compatible and submit a new PR

**Pull request closed without merging**
